name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: ${{ github.workspace }}/nacatgunma # Adjust path to your binary

    - name: Generate SLSA Provenance
      uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_generic.yml@v1.2.0
      with:
        go-version: '^1.23' # Must match the Go version used for building
        command: go build -v ./... # Must match the build command
        digest: ${{ jobs.slsa-build.outputs.digest }}
        upload-assets: true
#       provenance-upload-uri: ${{ github.event.inputs.provenance_upload_uri }} # Optional: for external storage

    - name: Upload Provenance Artifact
      if: steps.generate-provenance.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: provenance
        path: provenance.intoto.jsonl
