name: Go with SLSA Level 3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

permissions:
  id-token: write # to sign attestation
  contents: write # to upload assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for accurate provenance

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Artifacts
        id: upload-binary
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: ${{ github.workspace }}/nacatgunma # Adjust path to your binary

  generate-slsa:
    needs: build # Ensure 'build' job completes first
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.slsa_provenance.outputs.digest }} # Capture the digest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: go-binary
          path: built-binary

      - name: Calculate Digest
        id: calculate_digest
        run: |
          cd built-binary
          echo "digest=$(sha256sum nacatgunma | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Generate SLSA Provenance
        id: slsa_provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_generic.yml@v1.2.0
        with:
          go-version: '1.23'
          command: go build -v ./...
          digest: ${{ steps.calculate_digest.outputs.digest }}
          upload-assets: true

      - name: Upload Provenance Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: provenance.intoto.jsonl

