name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Generate SLSA3 provenance
      uses: slsa-framework/slsa-github-generator/actions/generic/generate-provenance@v1.9.0
      with:
        artifact-path: ./nacatgunma
